/*
$('table tbody tr').map((i, tr) => ({
	name: $(tr).children().eq(1).text().trim(),
	id: +$(tr).children().eq(1).find('a').attr('href').replace('/guide/mobs/', ''),
	level: +$(tr).children().eq(0).text().trim(),
})).get()
	.sort((a, b) => a.id - b.id);
 */

export default [
	{name: 'букавац', id: 1, level: 1},
	{name: 'призрачная одежда', id: 2, level: 2},
	{name: 'зазовка', id: 3, level: 4},
	{name: 'хищный кустик', id: 4, level: 5},
	{name: 'нук-секач', id: 5, level: 7},
	{name: 'бродячий дуб', id: 6, level: 8},
	{name: 'волк', id: 7, level: 10},
	{name: 'дух леса', id: 8, level: 11},
	{name: 'эльриада', id: 9, level: 13},
	{name: 'блюститель природы', id: 10, level: 14},
	{name: 'медведь', id: 11, level: 15},
	{name: 'аристократ', id: 12, level: 17},
	{name: 'единорог', id: 13, level: 18},
	{name: 'призрачный волк', id: 14, level: 19},
	{name: 'астральный охотник', id: 15, level: 21},
	{name: 'головоног', id: 16, level: 1},
	{name: 'домашний поползень', id: 17, level: 1},
	{name: 'гнилушь', id: 18, level: 3},
	{name: 'ползун', id: 19, level: 4},
	{name: 'сушилец', id: 20, level: 6},
	{name: 'гигантская росянка', id: 21, level: 7},
	{name: 'сбежавший эксперимент', id: 22, level: 9},
	{name: 'слизь', id: 23, level: 10},
	{name: 'гидра', id: 24, level: 12},
	{name: 'щупальце', id: 25, level: 13},
	{name: 'химический мусорник', id: 26, level: 15},
	{name: 'упырь', id: 27, level: 16},
	{name: 'кикимора', id: 28, level: 17},
	{name: 'бесхозный голем', id: 29, level: 19},
	{name: 'охотник за реагентами', id: 30, level: 20},
	{name: 'мутировавший гоблин', id: 31, level: 21},
	{name: 'василиск', id: 32, level: 21},
	{name: 'ожившее пугало', id: 33, level: 1},
	{name: 'хищный хомяк', id: 34, level: 2},
	{name: 'борец за справедливость', id: 35, level: 4},
	{name: 'клешнец', id: 36, level: 5},
	{name: 'маньяк', id: 37, level: 7},
	{name: 'карточный шулер', id: 38, level: 8},
	{name: 'богомол', id: 39, level: 10},
	{name: 'благородный разбойник', id: 40, level: 11},
	{name: 'одержимый колдун', id: 41, level: 13},
	{name: 'механический дракончик', id: 42, level: 14},
	{name: 'дварф-изгнанник', id: 43, level: 15},
	{name: 'неистовый сектант', id: 44, level: 17},
	{name: 'механический голем', id: 45, level: 18},
	{name: 'убийца', id: 46, level: 19},
	{name: 'полоумный маг', id: 47, level: 21},
	{name: 'шакал', id: 48, level: 1},
	{name: 'скорпион', id: 49, level: 1},
	{name: 'налётчик', id: 50, level: 3},
	{name: 'огненная лиса', id: 51, level: 4},
	{name: 'орк-изгнанник', id: 52, level: 6},
	{name: 'белый скарабей', id: 53, level: 7},
	{name: 'гремучая змея', id: 54, level: 9},
	{name: 'саламандра', id: 55, level: 10},
	{name: 'пустынный дракончик', id: 56, level: 12},
	{name: 'джинн', id: 57, level: 13},
	{name: 'берсерк', id: 58, level: 15},
	{name: 'смерч', id: 59, level: 16},
	{name: 'заблудший шаман', id: 60, level: 17},
	{name: 'шайтан', id: 61, level: 19},
	{name: 'крыса', id: 62, level: 1},
	{name: 'бандит', id: 63, level: 1},
	{name: 'призрак', id: 64, level: 7},
	{name: 'неупокоенный', id: 65, level: 15},
	{name: 'гремлин', id: 66, level: 1},
	{name: 'подыльник', id: 67, level: 3},
	{name: 'странствующий рыцарь', id: 68, level: 24},
	{name: 'нага', id: 69, level: 18},
	{name: 'охотник за головами', id: 70, level: 24},
	{name: 'суккуб', id: 71, level: 25},
	{name: 'вирика', id: 72, level: 1},
	{name: 'див', id: 73, level: 1},
	{name: 'додо', id: 74, level: 1},
	{name: 'ангиак', id: 75, level: 1},
	{name: 'бхут', id: 76, level: 1},
	{name: 'гвиллион', id: 77, level: 1},
	{name: 'вилах', id: 78, level: 1},
	{name: 'вендиго', id: 79, level: 1},
	{name: 'галд', id: 80, level: 1},
	{name: 'ачери', id: 81, level: 1},
	{name: 'земляная даппи', id: 82, level: 3},
	{name: 'огненная даппи', id: 83, level: 3},
	{name: 'анчутка', id: 84, level: 1},
	{name: 'жихарь', id: 85, level: 2},
	{name: 'йиена', id: 86, level: 10},
	{name: 'мара', id: 87, level: 19},
	{name: 'боец Серого Ордена', id: 88, level: 43},
	{name: 'спятивший лорд', id: 89, level: 21},
	{name: 'волколак', id: 90, level: 24},
	{name: 'медвелак', id: 91, level: 41},
	{name: 'аколит огня', id: 92, level: 28},
	{name: 'ламия', id: 93, level: 43},
	{name: 'баргест', id: 94, level: 22},
	{name: 'вий', id: 95, level: 42},
	{name: 'гьюнальский паук', id: 96, level: 42},
	{name: 'дэра', id: 97, level: 23},
	{name: 'гриндель', id: 98, level: 22},
	{name: 'грим', id: 99, level: 40},
	{name: 'кагир', id: 100, level: 37},
	{name: 'друджи', id: 101, level: 30},
	{name: 'даса', id: 102, level: 36},
	{name: 'ичетик', id: 103, level: 28},
	{name: 'кера', id: 104, level: 24},
	{name: 'куд', id: 105, level: 37},
	{name: 'ларва', id: 106, level: 29},
	{name: 'егви', id: 107, level: 27},
	{name: 'каменный великан', id: 108, level: 38},
	{name: 'каннибал', id: 109, level: 35},
	{name: 'ламашту', id: 110, level: 40},
	{name: 'лахама', id: 111, level: 26},
	{name: 'наркоман', id: 112, level: 22},
	{name: 'бывший палач', id: 113, level: 32},
	{name: 'мародёр', id: 114, level: 26},
	{name: 'страхолев', id: 115, level: 27},
	{name: 'злоцвет', id: 116, level: 32},
	{name: 'варвар', id: 117, level: 30},
	{name: 'ночная хныка', id: 118, level: 31},
	{name: 'омерзень', id: 119, level: 39},
	{name: 'смрадень', id: 120, level: 36},
	{name: 'глыдень', id: 121, level: 38},
	{name: 'песчаный холерник', id: 122, level: 39},
	{name: 'мать анаконд', id: 123, level: 31},
	{name: 'белая гиена', id: 124, level: 44},
	{name: 'мраморный бык', id: 125, level: 33},
	{name: 'язвомор', id: 126, level: 41},
	{name: 'лишайница', id: 127, level: 33},
	{name: 'жирница', id: 128, level: 35},
	{name: 'бульг', id: 129, level: 41},
	{name: 'костогрыз', id: 130, level: 34},
	{name: 'каменник', id: 131, level: 26},
	{name: 'вирница', id: 132, level: 9},
	{name: 'тигр', id: 133, level: 9},
	{name: 'барбегаз', id: 134, level: 12},
	{name: 'бродячий огонек', id: 135, level: 2},
	{name: 'скальник', id: 136, level: 23},
	{name: 'пупырник', id: 137, level: 24},
	{name: 'стогница', id: 138, level: 9},
	{name: 'гунила', id: 139, level: 18},
	{name: 'пёстробородый', id: 140, level: 28},
	{name: 'капитан Серых Плащей', id: 141, level: 45},
	{name: 'аколит льда', id: 142, level: 41},
	{name: 'семиглаз', id: 143, level: 12},
	{name: 'гюрза', id: 144, level: 8},
	{name: 'медвежук', id: 145, level: 15},
	{name: 'снежная росомаха', id: 146, level: 30},
	{name: 'койот', id: 147, level: 2},
	{name: 'горный манул', id: 148, level: 13},
	{name: 'мастер огня', id: 149, level: 33},
	{name: 'мастер льда', id: 150, level: 43},
	{name: 'кобольд', id: 151, level: 1},
	{name: 'пожиратель плоти', id: 152, level: 44},
	{name: 'главарь пёстробородых', id: 153, level: 38},
	{name: 'ученик Силы', id: 154, level: 11},
	{name: 'гомункул', id: 155, level: 10},
	{name: 'некромант', id: 156, level: 46},
	{name: 'тагар', id: 157, level: 52},
	{name: 'стрига', id: 158, level: 50},
	{name: 'приземник', id: 159, level: 48},
	{name: 'лесной тролль', id: 160, level: 50},
	{name: 'вурдалак', id: 161, level: 56},
	{name: 'болотный тролль', id: 162, level: 55},
	{name: 'бескуд', id: 163, level: 45},
	{name: 'атач', id: 164, level: 51},
	{name: 'камелопард', id: 165, level: 50},
	{name: 'невиданная тварь', id: 166, level: 1},
	{name: 'ырка', id: 167, level: 61},
	{name: 'шоток', id: 168, level: 58},
	{name: 'хрустальный барс', id: 169, level: 56},
	{name: 'галлу', id: 170, level: 48},
	{name: 'джудцгу', id: 171, level: 65},
	{name: 'изг', id: 172, level: 61},
	{name: 'ведомый', id: 182, level: 40},
	{name: 'комол', id: 189, level: 47},
	{name: 'ледяной тур', id: 190, level: 53},
	{name: 'нахцерер', id: 191, level: 54},
	{name: 'склеповник', id: 192, level: 60},
	{name: 'хала', id: 193, level: 45},
	{name: 'кумо', id: 194, level: 35},
	{name: 'мботата', id: 195, level: 33},
	{name: 'ракопаук', id: 196, level: 25},
	{name: 'иеля', id: 197, level: 20}
];
